on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Check nix flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v27
      - name: Check flake
        run: nix flake check --all-systems
      - name: Build helix package
        run: nix build
